version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    env_file:
      - .env
    environment:
      - SERVICES=${SERVICES}
      - DEBUG=${DEBUG}
      - DATA_DIR=${DATA_DIR}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - "${DATA_DIR}:/tmp/data"
    restart: unless-stopped
